#cloud-config
apt:
    preserve_sources_list: true

packages:
 - unzip
 - git
 - wget
 - apt-transport-https
 - software-properties-common
 - npm

 bootcmd:
  - mkdir -p /etc/systemd/system/walinuxagent.service.d
  - echo "[Unit]\nAfter=cloud-final.service" > /etc/systemd/system/walinuxagent.service.d/override.conf
  - sed "s/After=multi-user.target//g" /lib/systemd/system/cloud-final.service > /etc/systemd/system/cloud-final.service
  - systemctl daemon-reload